# Travis CI
language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0.4"

sudo: false

git:
  submodules: false

branches:
  only:
    - gh-pages

notifications:
  email:
    recipients:
      - SuriyaaKudoIsc@users.noreply.github.com
    on_success: change # default: change
    on_failure: always # default: always

before_script:
  - npm install

install:
  - gem install travis-lint
  - gem install jekyll
  - gem install html-proofer

script:
  - jekyll build
